config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('DashedRoute');

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Site', 'action' => 'dashboard']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    // $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('DashedRoute');
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/User.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * User Entity
 *
 * @property int $id
 * @property string $first_name
 * @property string $last_name
 * @property string $zipcode
 * @property string $address_street
 * @property string $address_number
 * @property string $address_neighborhood
 * @property string $address_city
 * @property string $address_state
 * @property string $phone
 * @property string $email
 * @property string $password
 */
class User extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];

    /**
     * Fields that are excluded from JSON versions of the entity.
     *
     * @var array
     */
    protected $_hidden = [
        'password'
    ];

    /**
     *
     **/
    protected $_virtual = ['full_name'];

    /**
     * Estado das atualizações
     **/
    const STATUS_PENDING        = 0;
    const STATUS_APPROVED       = 1;
    const STATUS_DISAPPROVED     = 2;

    /**
     *
     **/
    public function _getFullName()
    {
        return $this->first_name . ' ' .
            $this->last_name;
    }

    /**
     *
     **/
    public function _getStatusName()
    {
        if ($this->status == static::STATUS_DISAPPROVED) {
            return 'Desaprovado';
        }

        if ($this->status == static::STATUS_APPROVED) {
            return 'Aprovado';
        }

        if ($this->status == static::STATUS_PENDING) {
            return 'Pendente';
        }

    }
}

src/Model/Table/PaymentProductsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * PaymentProducts Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Payments
 * @property \Cake\ORM\Association\BelongsTo $Products
 *
 * @method \App\Model\Entity\PaymentProduct get($primaryKey, $options = [])
 * @method \App\Model\Entity\PaymentProduct newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\PaymentProduct[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\PaymentProduct|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\PaymentProduct patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\PaymentProduct[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\PaymentProduct findOrCreate($search, callable $callback = null)
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class PaymentProductsTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('payment_products');
        $this->displayField('id');
        $this->primaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Payments', [
            'foreignKey' => 'payment_id'
        ]);
        $this->belongsTo('Product', [
            'className' => 'Products',
            'foreignKey' => 'product_id'
        ]);

        $this->hasMany('Complements', [
            'className' => 'PaymentComplements',
            'foreignKey' => 'payment_product_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->numeric('size')
            ->allowEmpty('size');

        $validator
            ->numeric('amount')
            ->allowEmpty('amount');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['payment_id'], 'Payments'));
        $rules->add($rules->existsIn(['product_id'], 'Products'));

        return $rules;
    }
}

src/Model/Table/PaymentsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Payments Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Users
 * @property \Cake\ORM\Association\HasMany $PaymentComplements
 * @property \Cake\ORM\Association\HasMany $PaymentProducts
 *
 * @method \App\Model\Entity\Payment get($primaryKey, $options = [])
 * @method \App\Model\Entity\Payment newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Payment[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Payment|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Payment patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Payment[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Payment findOrCreate($search, callable $callback = null)
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class PaymentsTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('payments');
        $this->displayField('id');
        $this->primaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Users', [
            'foreignKey' => 'user_id'
        ]);
        $this->hasMany('Complements', [
            'className' => 'PaymentComplements',
            'foreignKey' => 'payment_id'
        ]);
        $this->hasMany('Items', [
            'className' => 'PaymentProducts',
            'foreignKey' => 'payment_id'
        ]);
    }

    /**
     *
     **/
    public function getPendings()
    {
        return $this->findByStatus(0);
    }

    /**
     *
     **/
    public function getActives()
    {
        return $this->find()
            ->where(['Payments.status !=' => 0]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->numeric('amount')
            ->allowEmpty('amount');

        $validator
            ->integer('status')
            ->allowEmpty('status');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['user_id'], 'Users'));

        return $rules;
    }
}

src/Model/Table/ProductsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

use App\Model\Entity\Image;

/**
 * Products Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Categories
 *
 * @method \App\Model\Entity\Product get($primaryKey, $options = [])
 * @method \App\Model\Entity\Product newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Product[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Product|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Product patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Product[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Product findOrCreate($search, callable $callback = null)
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class ProductsTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('products');
        $this->displayField('name');
        $this->primaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Categories', [
            'foreignKey' => 'category_id',
            'joinType' => 'INNER'
        ]);

        $this->hasMany('Images', [
            'foreignKey' => 'item_id',
            'conditions' => ['type' => Image::TYPE_PRODUCT]
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('name', 'create')
            ->notEmpty('name');

        $validator
            ->requirePresence('description', 'create')
            ->notEmpty('description');

        $validator
            ->requirePresence('price', 'create')
            ->notEmpty('price');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['category_id'], 'Categories'));

        return $rules;
    }
}

src/Template/Panel/categories_manager.ctp
<?php
$this->layout('panel');
$this->assign('crumb-panel', 'categories');
?>
<section id="panel-products-manager">
	<h1 class="main-page-title"><i class="fa fa-reorder"></i> Categorias</h1>
	<div class="content-padding-wrap">
		<div class="form-group text-right">
			<a href="<?= $this->Url->build(['controller' => 'Panel', 'action' => 'categoryAdd']) ?>" class="btn btn-success"><i class="fa fa-plus"></i> Nova categoria</a>
		</div>
		<!-- Lista de categorias -->
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<!-- Mensagem de sucesso -->
				<?php if ($this->request->query('status') == 'success'): ?>
				<div class="alert alert-success">
					<!-- Adicionando -->
					<?php if ($this->request->query('action') == 'add'): ?>
					<p><i class="fa fa-check"></i> Categoria adicionada com sucesso</p>
					<?php endif ?>
					<!-- Adicionando -->
					<!-- Editando -->
					<?php if ($this->request->query('action') == 'edit'): ?>
					<p><i class="fa fa-check"></i> Categoria editada com sucesso</p>
					<?php endif ?>
					<!-- Editando -->
					<!-- Excluindo -->
					<?php if ($this->request->query('action') == 'delete'): ?>
					<p><i class="fa fa-check"></i> Categoria excluída com sucesso</p>
					<?php endif ?>
					<!-- Excluindo -->
				</div>
				<?php endif ?>
				<!-- Mensagem de sucesso -->
				<table class="table table-striped table-bordered body-middle text-centered">
					<thead>
						<tr>
							<th></th>
							<th width="250" align="center">Nome</th>
							<th>Sub-Categorias</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($categories as $category): ?>
						<tr>
							<td>
								<a href="<?= $this->Url->build(['controller' => 'Panel', 'action' => 'categoryEdit', $category->id]) ?>" class="btn btn-xs btn-success"><i class="fa fa-cog"></i> Editar</a>
							</td>
							<td><strong><?= $category->name ?></strong></td>
							<td>
								<?php foreach ($category->child_categories as $child): ?>
								<p><a href="<?= $this->Url->build(['controller' => 'Panel', 'action' => 'categoryEdit', $child->id]) ?>""><?= $child->name ?></a></p>
								<?php endforeach ?>
							</td>
						</tr>
						<?php endforeach ?>
					</tbody>
				</table>
			</div>
		</div>
		<!-- Lista de categorias -->
	</div>
</section>

src/Template/Panel/category_add.ctp
<?php
$this->layout('panel');
$this->assign('crumb-panel', 'categories');
?>
<section id="panel-products-manager">
	<h1 class="main-page-title">
		<?php if ($this->request->action == 'categoryAdd'): ?>
		Adicionando categoria
		<?php else: ?>
		Alterando categoria
		<?php endif ?>
	</h1>
	<div class="content-padding-wrap">
		<!-- Formulário -->
		<?= $this->Form->create($categoryEntity) ?>
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="form-group">
					<?= $this->Form->input('name', [
						'label' => 'Nome',
						'class' => 'form-control'
					]) ?>	
				</div>
				<div class="form-group">
					<?= $this->Form->input('parent_id', [
						'label' => 'Categoria pai',
						'class' => 'form-control',
						'options' => ['0' => 'Nenhuma'] + $categoriesOption,
						'id' => 'product-add-category-select'
					]) ?>	
				</div>	
				<button class="btn btn-success">Salvar</button>
				<?php if ($this->request->action == 'categoryEdit'): ?>
				<div class="pull-right">
					<a href="<?= $this->Url->build(['controller' => 'Panel', 'action' => 'categoryDelete', $categoryEntity->id]) ?>" class="btn btn-danger" onclick="return confirm('Tem certeza que deseja exclui esta categoria PERMANENTEMENTE?')">Excluir</a>
				</div>
				<?php endif ?>
			</div>
		</div>
		<?= $this->Form->end() ?>
		<!-- Formulário -->
	</div>
</section>

src/Template/Panel/dashboard.ctp
<?= $this->layout('panel') ?>
dashboard

src/Template/Panel/payment_view.ctp
<?php 
	$this->layout('panel');
	$this->assign('crumb-panel', 'payments');
?>

<section id="page-payment-view">
	<h1 class="main-page-title">Visualizando fatura</h1>
	<div class="content-padding-wrap">
	<!-- Mensagem de status -->
	<?php if ($this->request->query('action') == 'status' && $this->request->query('status') == 'success'): ?>
	<div class="alert alert-success">
		<span><i class="fa fa-check"></i> <b>Fatura editada com sucesso!</b></span>
	</div>
	<?php endif ?>
	<!-- Mensagem de status -->
	<?= $this->Form->create($paymentEntity) ?>
	<div class="row">
		<div class="col-sm-12">
			<div class="text-center">
				<div><b>Marcar como:</b></div>
				<a href="<?= $this->Url->build(['controller' => 'Panel', 'action' => 'paymentSet', $paymentEntity->id, 1]) ?>" class="btn btn-lg btn-success">
					<i class="fa fa-thumbs-up"></i> Pago
				</a>
				<a href="<?= $this->Url->build(['controller' => 'Panel', 'action' => 'paymentSet', $paymentEntity->id, 2]) ?>" class="btn btn-lg btn-danger"><i class="fa fa-thumbs-down"></i> Cancelado</a>
			</div>
			<hr />
			<h1>
				<?php if ($paymentEntity->status == 0): ?>
				<span class="label label-warning">Pendente</span>
				<?php elseif($paymentEntity->status == 1): ?>
				<span class="label label-success">Aprovado</span>
				<?php else: ?>
				<span class="label label-danger">Cancelado</span>
				<?php endif ?>
			</h1>
			<hr />
			<h2>Cliente</h2>
			<div class="row">
				<div class="col-sm-6">
					<div class="form-group">
						<b>Nome</b>	
						<div><?= $paymentEntity->user->full_name ?></div>
					</div>
					<div class="div">
						<b>CPF / CNPJ</b>	
						<div><?= $paymentEntity->user->document ?></div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="form-group">
						<b>Endereço</b>	
						<div><?= $paymentEntity->user->address_street ?>, <?= $paymentEntity->user->address_neighborhood ?></div>
						<div><?= $paymentEntity->user->address_city ?> - <?= $paymentEntity->user->address_state ?>, <?= $paymentEntity->user->zipcode ?></div>
					</div>
					<div class="div">
						<b>Email</b>	
						<div><?= $paymentEntity->user->email ?></div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="col-sm-12">
			<hr />
		</div>

		<div class="col-sm-12">
			<h2>Fatura</h2>
			<div class="row">
				<div class="col-md-6">
					<b>Data</b>	
					<div><?= $paymentEntity->created->format('d/m/Y') ?></div>
				</div>
				<div class="col-md-6">
					<b>Valor</b>	
					<div>R$<?= number_format($paymentEntity->amount, 2, ',', '.') ?></div>
				</div>
				<div class="col-md-12">
					<hr />
					<panel class="panel-info">
						<div class="panel-heading"><b>Produtos</b></div>
						<table class="table">
							<thead>
								<tr>
									<th>#</th>
									<th>Nome</th>
									<th>Tamanho</th>
								</tr>
							</thead>
							<tbody>
								<?php foreach ($paymentEntity->items as $item): ?>
								<tr>
									<td><?= $item->product->id ?></td>
									<td>
										<strong><?= $item->product->name ?></strong>
										<ul>
											<?php foreach ($item->complements as $complement): ?>
											<li><i><?= $complement->complement->name ?> - <?= sprintf("%.3fm", $complement->size) ?></i></li>
											<?php endforeach ?>
										</ul>
									</td>
									<td><?= sprintf("%.3fm", $item->size) ?></td>
								</tr>
								<?php endforeach ?>
							</tbody>
						</table>
					</panel>
				</div>
			</div>
		</div>
	</div>
	<?= $this->Form->end() ?>
	</div>
</section>

src/Template/Panel/payments_manager.ctp
<?php 
	$this->layout('panel');
	$this->assign('crumb-panel', 'payments');
?>

<section id="page-product-add">
	<h1 class="main-page-title"><i class="fa fa-money"></i> Faturas</h1>
	<div class="content-padding-wrap">
		<!-- Mensagem de status -->
		<?php if ($this->request->query('action') == 'status' && $this->request->query('status') == 'success'): ?>
		<div class="alert alert-success">
			<span><i class="fa fa-check"></i> <b>Fatura editada com sucesso!</b></span>
		</div>
		<?php endif ?>
		<!-- Mensagem de status -->
		<!-- Tabela de faturas pendentes -->
		<div class="panel panel-info">
			<div class="panel-heading"><span><i class="fa fa-clock-o"></i> <b>Existem <?= $paymentsPendingEntity->count() ?> orçamentos aguardando aprovação</b></span></div>
			<table class="table table-striped">
				<thead>
					<tr>
						<th></th>
						<th>Cliente</th>
						<th>Status</th>
						<th>Valor</th>
						<th>Emissão</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($paymentsPendingEntity as $payment): ?>
					<tr class="warning">
						<td>
							<div class="btn-group">
								<button 
									class="btn btn-xs btn-primary dropdown-toggle" data-toggle="dropdown">
									<i class="fa fa-cogs"></i> Opções <span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li>
										<a href="<?= $this->Url->build(['controller' => 'Panel', 'action' => 'paymentView', $payment->id]) ?>" ><i class="fa fa-eye"></i> Visualizar</a>
									</li>
									<li class="divider"></li>
									<li>
										<a href="<?= $this->Url->build(['controller' => 'Panel', 'action' => 'paymentSet', $payment->id, 1]) ?>"><span class="text-success"><i class="fa fa-check"></i> Marcar como paga</span></a>
									</li>
									<li>
										<a href="<?= $this->Url->build(['controller' => 'Panel', 'action' => 'paymentSet', $payment->id, 2]) ?>"><span class="text-danger"><i class="fa fa-close"></i> Marcar como cancelada</span></a
									</li>
								</ul>
							</div>
						</td>
						<td><?= $payment->user->full_name ?></td>
						<td>
							<div class="span label label-xs label-warning">Pendente</div>
						</td>
						<td><?= $payment->amount_cash ?></td>
						<td><?= $payment->created->format('d/m/Y') ?></td>
					</tr>
					<?php endforeach ?>
					<?php foreach ($paymentsActiveEntity as $payment): ?>
					<tr>
						<td>
							<div class="btn-group">
								<button 
									class="btn btn-xs btn-primary dropdown-toggle" data-toggle="dropdown">
									<i class="fa fa-cogs"></i> Opções <span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li>
										<a href="<?= $this->Url->build(['controller' => 'Panel', 'action' => 'paymentView', $payment->id]) ?>" ><i class="fa fa-eye"></i> Visualizar</a>
									</li>
									<li class="divider"></li>
									<li>
										<a href="<?= $this->Url->build(['controller' => 'Panel', 'action' => 'paymentSet', $payment->id, 1]) ?>"><span class="text-success"><i class="fa fa-check"></i> Marcar como paga</span></a>
									</li>
									<li>
										<a href="<?= $this->Url->build(['controller' => 'Panel', 'action' => 'paymentSet', $payment->id, 2]) ?>"><span class="text-danger"><i class="fa fa-close"></i> Marcar como cancelada</span></a
									</li>
								</ul>
							</div>
						</td>
						<td><?= $payment->user->full_name ?></td>
						<td>
							<?php if ($payment->status == 1): ?>
							<span class="label label-xs label-success">Paga</span>
							<?php else: ?>
							<span class="label label-xs label-danger">Cancelada</span>
							<?php endif ?>
						</td>
						<td><?= $payment->amount_cash ?></td>
						<td><?= $payment->created->format('d/m/Y') ?></td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>
			<!-- Paginação -->
			<?= $this->Element('Panel/pagination') ?>
			<!-- Paginação -->
		</div>
		<!-- Tabela de faturas pendentes -->
	</div>
</section>

src/Template/Panel/products_manager.ctp
<?php
	$this->layout('panel');
	$this->assign('crumb-panel', 'products');
?>
<section id="panel-products-manager">
	<h1 class="main-page-title"><i class="fa fa-shopping-cart"></i> Produtos</h1>
	<div class="content-padding-wrap">
		<div class="form-group text-right">
			<a href="<?= $this->Url->build(['controller' => 'Panel', 'action' => 'productAdd']) ?>" class="btn btn-success"><i class="fa fa-plus"></i> Novo produto</a>
		</div>
		<!-- Busca de usuários -->
		<?= $this->Element('Panel/search-input', [
			'placeholder' => 'Buscar produto'
		]) ?>
		<!-- Busca de usuários -->

		<!-- Lista de produtos -->
		<table class="table body-middle table-striped">
			<thead>
				<tr>
					<th width="115"></th>
					<th width="80"></th>
					<th>#</th>
					<th>Nome</th>
					<th>Categoria</th>
					<th>Valor</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($products as $product): ?>
				<tr>
					<td valign="middle">
						<div class="btn-group">
							<button 
								class="btn btn-xs btn-primary dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-cogs"></i> Opções <span class="caret"></span>
							</button>
							<ul class="dropdown-menu">
								<li>
									<a href="#" ><i class="fa fa-cog"></i> Editar</a>
								</li>
							</ul>
						</div>
					</td>
					<td>
						<img width="40" height="40" src="<?= $this->Url->build('/uploads/' . $product->thumb) ?>">
					</td>
					<td valign="middle"><?= $product->id ?></td>
					<td valign="middle"><?= $product->name ?></td>
					<td valign="middle"><?= $product->category->name ?></td>
					<td valign="middle"><?= $product->price_money_format ?></td>
				</tr>
				<?php endforeach ?>
			</tbody>
		</table>
		<!-- Lista de produtos -->

		<!-- Paginação -->
		<?= $this->Element('Panel/pagination', [
			'hashtag' => '#'
		]) ?>
		<!-- Paginação -->
	</div>
</section>